package org.beta.tchap.identite.utils;

public interface Constants {

    String TCHAP_ACCOUNT_EMAIL = "TCHAP_ACCOUNT";
    String TCHAP_PASSWORD = "TCHAP_PASSWORD";
    String TCHAP_HOME_SERVER_LIST = "TCHAP_HOME_SERVER_LIST";
    String TCHAP_SKIP_CERTIFICATE_VALIDATION = "TCHAP_SKIP_CERTIFICATE_VALIDATION";
    String TCHAP_UNAUTHORIZED_HOME_SERVER_LIST = "TCHAP_UNAUTHORIZED_HOME_SERVER_LIST";
    String TCHAP_MATRIX_ID = "TCHAP_MATRIX_ID";

    String TCHAP_LOG_SENSITIVE_DATA = "TCHAP_LOG_SENSITIVE_DATA";

    String TCHAP_OTP_MAIL_DELAY_IN_MINUTES = "TCHAP_OTP_MAIL_DELAY_IN_MINUTES";
    String TCHAP_CODE_TIMEOUT_IN_MINUTES = "TCHAP_CODE_TIMEOUT_IN_MINUTES";

    String FEATURE_TCHAP_BOT_OTP = "FEATURE_TCHAP_BOT_OTP";
}
