name: Build jar of tchap-identite

on:
  push:
    branches:
      - '**'      # matches every branch
      - '!main'   # excepted main

jobs:
  build-jar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        run: echo "${{ needs.tag-version.outputs.new_version }}"
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -Drevision=${{ needs.tag-version.outputs.new_version }} -B package --file pom.xml
