# This is a basic workflow to help you get started with Actions

name: Build jar of tchap-identite #major #minor #patch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Auto tag version of tchap-identite
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

  build-jar:
    needs: [tag-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  create-release:
    needs: [tag-version, build-jar]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get release version
        run: echo "The new release is ${{needs.tag-version.outputs.new_tag}}"
      - name: Create tchap-identite release
      - uses: ncipollo/release-action@v1
        with:
          name: ${{needs.tag-version.outputs.new_tag}}
          tag: ${{needs.tag-version.outputs.new_tag}}
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}