name: Build jar of authentification-core #major #minor #patch

on:
  push:
    branches: [ main ]

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Auto tag version of authentification-core
        id: tag_version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
    outputs:
      new_version :  ${{ steps.tag_version.outputs.new_tag }}

  build-jar:
    needs: [tag-version]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        run: echo "${{ needs.tag-version.outputs.new_version }}"
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -Drevision=${{ needs.tag-version.outputs.new_version }} -B package --file pom.xml
      - name: Create authentification-core release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.tag-version.outputs.new_version }}
          generateReleaseNotes: true
          artifacts: "/home/runner/work/tchap-identite/tchap-identite/dev/providers/authentification-core-${{ needs.tag-version.outputs.new_version }}.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
