name: Build jar of tchap-identite #major #minor #patch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Auto tag version of tchap-identite
        id: tag_version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
    outputs:
      new_version :  ${{ steps.tag_version.outputs.new_tag }}

  build-jar:
    needs: [tag-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        run: echo "${{ needs.tag-version.outputs.new_version }}"
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml